defmodule DemoAdmin.Repo.Migrations.CreateMemberships do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:memberships, primary_key: false) do
      add :user_id,
          references(:users,
            column: :id,
            name: "memberships_user_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ), primary_key: true, null: false

      add :office_id,
          references(:offices,
            column: :id,
            name: "memberships_office_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ), primary_key: true, null: false
    end

    create index(:memberships, [:user_id])
  end

  def down do
    drop_if_exists index(:memberships, [:user_id])

    drop constraint(:memberships, "memberships_user_id_fkey")

    drop constraint(:memberships, "memberships_office_id_fkey")

    drop table(:memberships)
  end
end
